In [1]:
import torch
from fit_sigmoid import sigmoid2linear

X = torch.randn(1, 2, 2, 3)
X[0, :10]

tensor([[[-0.5492,  0.7232,  0.4455],
         [ 0.2058,  0.4714,  0.7740]],

        [[ 0.8725, -1.5342,  1.1839],
         [ 1.1853, -0.7816, -1.0157]]])

In [2]:
torch.sigmoid(X)[0, :10]

tensor([[[0.3660, 0.6733, 0.6096],
         [0.5513, 0.6157, 0.6844]],

        [[0.7053, 0.1774, 0.7656],
         [0.7659, 0.3140, 0.2659]]])

In [3]:
Y = sigmoid2linear(X)
Y[0, :10]

tensor([[[0.3660, 0.6733, 0.6063],
         [0.5484, 0.6125, 0.6856]],

        [[0.7094, 0.1282, 0.7846],
         [0.7849, 0.3099, 0.2534]]])

In [4]:
from fixed_sigmoid import linear_sigmoid
linear_sigmoid(X)[0, :10]

tensor([[[0.3731, 0.6671, 0.6029],
         [0.5476, 0.6089, 0.6788]],

        [[0.7016, 0.1889, 0.7586],
         [0.7588, 0.3194, 0.2666]]])

In [5]:
torch.sigmoid(X)[0, :10]

tensor([[[0.3660, 0.6733, 0.6096],
         [0.5513, 0.6157, 0.6844]],

        [[0.7053, 0.1774, 0.7656],
         [0.7659, 0.3140, 0.2659]]])